### ISSUE TITLE
On phone: tell the user to open the hamburger menu to enable a POI category

### ISSUE THREAD

**Issue by carstenhag** [babykarte/babykarte.github.io#109]
Currently, when first opening the website, the site asks for the user's location. After being granted it zooms there and nothing happens.

Instead, either a few POI categories should be enabled per default or the user should be told that categories can be enabled in the menu.

**Comment by ValorNaram** [comment]
# Thank you for your feedback

We're trying to do our best to make Babykarte a great open-source tool for parents and other persons who have also interest in "baby related things". That's why appreciate your feedback. To come to the points you mentioned:

> Currently, when first opening the website, the site asks for the user's location. After being granted it zooms there and nothing happens.

Are you sure that you don't pressed the locating button on the top right site on the map? Babykarte will only ask you, if you press the locating button.

> Instead, either a few POI categories should be enabled per default or the user should be told that categories can be enabled in the menu.

As you know I mentioned that in #92 but we have had some difficulties deciding which filter aka POI category we would like to have enabled by default so we stoped going further.

**Comment by ValorNaram** [comment]
> Hey! Yeah, of course I pressed that button, I just forgot to write that :D

Glad to hear that. There's a popup notifying you about the map change. If no filters are selected, nothing will happen.

> How about a tooltip/info window that gets displayed only when no filter is chosen?

That would be possible and easy to achieve.

**Comment by ValorNaram** [comment]
> How about a tooltip/info window that gets displayed only when no filter is chosen?

**Done, see https://github.com/babykarte/babykarte.github.io/commit/6aed3b2d30f4958169aa5beaca81728f10c6cc94**

> Instead, either a few POI categories should be enabled per default

We have had that discussion some time ago but we did not go further on. I personally think that **this approach is user unfriendly** but I assigned the team members of Babykarte and you so we can discuss this.

**Should Babykarte have some filters selected by default?**

**Comment by Discostu36** [comment]
I haven't looked at it yet but in general I think a tooltip is better than standard filters selected.

**Comment by ValorNaram** [comment]
No one said something else. I am closing this because I implemented all points from above. We're still waiting for the translations to be complete.
