### ISSUE TITLE
Contact NoCashMaps to perhaps work on a common map project

### ISSUE THREAD

**Issue by carstenhag** [babykarte/babykarte.github.io#114]
Hey, basically I think https://nocashmaps.com/ and the baby map do similar things, just with a different focus. Frankly, their frontend design is really pretty and seems to be adaptable to this project's needs. They query overpass via websockets (not really sure why) and use Mapbox's maps.

It would be good if we contact them. Afaik it's not open-source yet, but that could change. They also have a twitter handle, https://twitter.com/NoCashMaps.

**Comment by ValorNaram** [comment]
I don't know, if we want it. We need to check that.

I am currently thinking about a bar at the bottom or top of Babykarte that behaves smart especially on mobile devices. I did not come to the planning and developing yet but this design change will come because it is more user friendly then a menu as we currently have. But design changes need huge thinking and planning and some development time. Thinking about a good design takes usually most of the time in web designing.

**Comment by Discostu36** [comment]
Their design looks a bit more modern than ours. But the data is loading so slowly (at least on my mobile) that it's super frustrating to use. So I don't think we should use their code.

What I find interesting is the possibility to constantly show your position on the map. On the other hand it might be problematic concerning privacy.

@carstenhag: What do you like best about their design? What do you think we should adopt?

**Comment by ValorNaram** [comment]
**Closed for inactivity**
