### ISSUE TITLE
Add marker color to filter selection

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#33]
Please add the colors of the markers to the filter selection (e.g. as a little dot or little square between check box and word). This way it's easier to see what kind of POI the marker does indicate.

**Comment by ValorNaram** [comment]
**Sub-Issue:** Reduce the amount of 17ten marker symbols to just one symbol which colour can be changed via CSS.

**Comment by Discostu36** [comment]
Too small, colors are not distinguishable. Please make at least as big as the small letters.

**Comment by ValorNaram** [comment]
Please make at least as big as the small letters.

Not possible because it is a special unicode char. Setting its font size would also the increase the font size of the text which I don't want to happen. I found another approach. Please pull again and see what I did in order to solve this issue.

Please close this when you're happy.

**Comment by Discostu36** [comment]
I'm not quite hapy yet. But, luckily, Unicode has some other symbols available :-)

`<span style="color: rgb(135, 0, 0); font-weight: bold; font-size: 16px;vertical-align: top;">&#9632; </span>`
