### ISSUE TITLE
Zoom problems

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#37]
There is still some buggy behavior when zooming out after applying a filter. Quite often, not all markers are shown that should be shown.

Maybe we should remove the dynamic loading of additional POIs? Then we could just rename the button from "Apply filters" to "Refresh map" and the user has to refresh every time when changing selection *or* map view.

But this is of course not very convenient, especially on a mobile device. Do you know another way how to fix this?

**Comment by ValorNaram** [comment]
I know the bug but I don't find a good solution. Theoretically I have an idea for a algorythm but I am not quite happy with this.

**Comment by Discostu36** [comment]
Could you explain how the website now loads new content when the bounding box is changed? Maybe I can think of some other way that doesn't lead to this error.

In my opinion this is the only thing that still needs to be fixed before officially releasing v1.

**Comment by ValorNaram** [comment]
When move ends the website calculates the new south, new north, new east and the new west endpoints by using the data from the state before to calculate and mimik just the added data the user requested instead of reloading the whole map view which could also have old data included. My algorithm detects for this purpose how much the map has been moved by user and requests just the data for the moved area of the map. It requests just the data for the move range (range the map was moved by user)

**Comment by Discostu36** [comment]
OK, sounds reasonable. Any chance that you find out how to fix the algorithm? Could you maybe analyze the source code of some other (open source) OpenStreetMap projects and find out how they managed it?

If we can't fix it, we have to reload the whole data after every move. It's bad for performance but incomplete data isn't helpful for the user.

**Comment by ValorNaram** [comment]
I can't provide a appropriate solution as fast as you want. A quick reminder: I need to obey my own  philosophy of how to do it right, provide as much performance as possible and shorten the query sent to Overpass as possible in order to have Overpass answer the requests as fast as possible.

This three cornerstones have increased Babykartes performance a lot. You might remember yourself when Babykarte ran slow regarding Overpass queries. By creating and following the rules I made myself I can keep the quality as it is now at least. Maybe I even increase the quality of Babykarte. That's the hope of every developer, to increase the quality of their work and products.

Please also remember that I am not a trained developer, I teach software developing myself by reading tutorials you can find on the web like sand on the beach.

**Comment by ValorNaram** [comment]
> Maybe we should remove the dynamic loading of additional POIs? Then we could just rename the button from "Apply filters" to "Refresh map"

Why should we do this.

>  Do you know another way how to fix this?

Yes.
1) Including the button in the bar that is always shown on mobile devices or
2) I manage to develop a more bug-free solution that fits best to Babykarte

**Comment by Discostu36** [comment]
> I can't provide a appropriate solution as fast as you want. 

I don't want to give you any pressure. But I'd prefer a bug free version of Babykarte to release as v1. I'd be willing to sacrifice performance for this, even if this means to resend the whole query after every change of the bounding box. But maybe you are of a different opinion.

In my opinion completeness of data shown is more important than performance. But.your opinion may be different.

**Comment by ValorNaram** [comment]
I understand the reason behind that. It's possible that it reloads all POIs until a solution can be found

**Comment by ValorNaram** [comment]
**I will work on this along, please do not close this issue.**

The algorithm is now deactivated and replaced by a simpler one

**Comment by Discostu36** [comment]
Great, thanks. In most cases reloading takes less than a second. I think this is totally acceptable.

**Comment by Discostu36** [comment]
https://forum.openstreetmap.org/viewtopic.php?pid=743151#p743151

**Comment by plepe** [comment]
Feel free to use https://github.com/plepe/overpass-frontend. It caches data in the browser and splits queries into several requests (requesting only n elements per request). It builds the basis of https://www.openstreetbrowser.org/

**Comment by ValorNaram** [comment]
I found a workaround for this and the user @mmd from the OSM forum `users: Germany` also wrote how to shorten the overpass request.

Read his message here:
https://forum.openstreetmap.org/viewtopic.php?pid=743456#p743456

**Comment by ValorNaram** [comment]
Some problems with attaching the zoom event, it does not get fired by leaflet.

**Comment by Discostu36** [comment]
As soon as this is fixed I'd like to release a v.1.1 with the progress we've made so far.
