### ISSUE TITLE
Group markers that are very close to each other

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#51]
Maybe this can be useful:

https://server.boundlessgeo.com/docs/latest/cartography/rt/pointstacker.html

**Comment by ValorNaram** [comment]
I **hate** clustering of markers and I think this feature will annoy some users.

**Comment by Discostu36** [comment]
what is your preferred solution for markers that are too close to each other for the chosen zoom level?

**Comment by ValorNaram** [comment]
I don't know. I will work on an appropriate solution that doesn't negatively affect the performance.

**Comment by ValorNaram** [comment]
I implemented it but I'm not quite happy about it: Especially the performance

Perhaps I find a solution but no promises.

**Comment by ValorNaram** [comment]
## Implementation failure

The implementation of `markercluster` failed due to the following reasons.
* at certain times in runtime the markercluster needs to be deactivated (not possible since I don't know how) in order to increase performance
* Markers are hidden for Babykarte when clustered. (Removal and adding of markers aren't under control of Babykarte)


This issue has been labeled `wontfix`.

Feel free to comment here and I will see how to support you (helping to understand my code etc.) when you consider helping me.

**Comment by ValorNaram** [comment]
**Closing this because this technique is user-unfriendly** due to the following reasons:

## Problem
- It forces the user to zoom more and so it leads to more downloading of map tiles and therefore more data usage. And as last: It's getting users on their nerves.
- Users can control the load of markers and dots by (de)activating filters.

## How can we do better?
I can think of another implementation that do

- organise the map in a way which is helpful and effective for users
- help users finding what they're looking for more fast and with reliable results.

For both points the [wheelmap](https://wheelmap.org/) is a good example of how it can be.
