### ISSUE TITLE
Button to select/deselect all filters

### ISSUE THREAD

**Issue by waldyrious** [babykarte/babykarte.github.io#68]
Currently one needs to select the checkboxes one by one. It would be more convenient if there was a button to select/deselect them all.

Additionally, I think it could make sense to have at least 2 or 3 categories selected by default when the page first loads, so that the map shows at least somethings and immediately demonstrates what the tool is about.

**Comment by ValorNaram** [comment]
#### Welcome to 'Babykarte' project. Thanks for your feedback. We will consider it as soon as possible.

But there are some questions I have regarding to your request.

> [...] if there was a button to select/deselect them all.

I agree a button or even better symbol to deselect them all would be nice but also having the option to select them all at once? Seems questionable because which user wants to select them all at once? The filters exist to let the user decide what he/she wants to see and to make life easier (increasing useability by filtering out unneeded points of interests (POI's))

> Additionally, I think it could make sense to have at least 2 or 3 categories selected by default [...] so that the map shows at least somethings and immediately demonstrates what the tool is about.

@Discostu36 and I had such idea but we didn't go further. See #55 for reference. I agree with you but then we need to ask ourselves which filter we'd like to have selected by default.

**Comment by waldyrious** [comment]
> which user wants to select them all at once?

It could help e.g. identifying areas of higher density of child-related facilities, or learning about nearby amenities that one might not think of explicitly searching for. FWIW, I'd fit into the second category myself.

**Comment by ValorNaram** [comment]
> It could help e.g. identifying areas of higher density of child-related facilities [..]  that one might not think of explicitly searching for.

Mhhh. Do you an opinion on this, @Discostu36? I am personally skeptical hence my questions. This feature request is easy to implement but should babykarte also be a tool for research related things like
> [...] identifying areas of higher density of child-related facilities [...]

?

**Implementing this feature won't clutter the user interface.**

**Comment by ValorNaram** [comment]
I implemented your feature request for now. It will take effect when v2.0 of Babykarte is being released. This will take some time.

**Thank you for improving this project by suggestions/feature requests. We appreciate that, really**

I think we can close this.
