### ISSUE TITLE
Description=undefined

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#81]
![image](https://user-images.githubusercontent.com/30999326/58282222-66d7b800-7da5-11e9-87f0-5d7e81eb482f.png)

**Comment by ValorNaram** [comment]
You can also share the url Babykarte points to when you click on the map. I standardized your test environment with mine so we can exchange and point to positions on the virtual globe inside Babykarte-devel. Take a look at the urls in #66. You can just open it when you run the test environment for Babykarte-devel. This makes my work, my validations and yours easier.


PS: This bug occurred because I did a mistake in my past validations for #38 

**This bug has been fixed.**

**Comment by Discostu36** [comment]
http://localhost:8080/#16&54.334705565484796&10.138083458296025

Now diaper and highchair are missing :-)

![grafik](https://user-images.githubusercontent.com/30999326/58354558-25610e80-7e72-11e9-8ff9-04e97d197d6e.png)

**Comment by ValorNaram** [comment]
This is going to drive me crazy.

**Second Bugfix provided**
