### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by NicolasGrosjean** [babykarte/babykarte.github.io#94]
Hello,

I am interested to translate babykarte into French.

Like asked in [CONTRIBUTING.md](https://github.com/babykarte/babykarte.github.io/blob/master/CONTRIBUTING.md), I create an issue before starting a pull request.

I have seen a closed translation issue (#73), if I understand well, to translate babykarte into French, I need to translate both [privacypolicy-en.html](https://github.com/babykarte/babykarte.github.io/blob/master/privacypolicy-en.html) and [en.js](https://github.com/babykarte/babykarte.github.io/blob/master/js/en.js) (I am not a German speaker).

For en.js, the translation should like the following example, right ?
```
var refFr = {"site-map": {
	"LOCATING_FAILURE": "N'a pas trouvé votre lieu",
[...]
registerLang("fr", refFr);
setLang("", "fr");
```

I think there is also some work to add a French flag, link files, ... But this work should be very easy or doable by another contributor, right ?

**Comment by ValorNaram** [comment]
Hello @NicolasGrosjean,

we are happy to have someone who can do the translation in french.

We are very sorry that we have to force translators to translate also the privacy policy. This is required by law because not every single internet user can speak and read english. Beside this we have also the problem of keeping translations up-to-date but using translation services may be possible for us except for the privacy policy.

Country flags are in the public domain and therefore easy to get.

We will preprocess your contribution before it goes online. Just push your translation files to the `devel` branch and we will add "french" to our system.

Files you have to push:
- A valid `js/fr.js` (JSON format)
- A valid `privacypolicy-fr.md` (Markdown format)

Templates:
- Use `js/en.js` as template for `js/fr.js`
- Use `privacypolicy.md` as template for `privacypolicy-fr.md`


**You don't have to speak any german in order to contribute to this project. We are international :)**


Michael has to agree because the Webapp runs under this name and responsibility. An impress is also required by law.

**Comment by NicolasGrosjean** [comment]
Thank you @ValorNaram for the precisions.

**Comment by NicolasGrosjean** [comment]
[Pull request merged](https://github.com/babykarte/babykarte.github.io/pull/95)
